
// This file was auto-generated by ML.NET Model Builder. 

using CatAndDogClassificatorModel_TestConsoleApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\shmac\src\RUDN\Polynoms\AI\Samples\Cat\00000109.jpg");
CatAndDogClassificatorModel.ModelInput sampleData = new CatAndDogClassificatorModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = CatAndDogClassificatorModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
